version: 0.1.0
# master
-
  branches:
    only:
      - master 
  skip_tags: true

  clone_depth: 1

  build:
    parallel: true
    publish_nuget: true
    verbosity: quiet

  os: Visual Studio 2017

  build_script:
    - ps: $env:BUILD_VERSION = $env:appveyor_build_version
    - ps: .\build.ps1

  on_failure:
    - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version)-$(Get-Date -format HHmmss)-failed"    
    - ps: $wc = New-Object 'System.Net.WebClient'
    - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
    

  on_success:
    - ps: $wc = New-Object 'System.Net.WebClient'
    - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))

-
  branches:
    except:
      - master
  skip_tags: true

  clone_depth: 1

  build_script:
    - ps: $env:BUILD_VERSION = $env:appveyor_build_version
    - ps: .\build.ps1

  on_success:
    - ps: $wc = New-Object 'System.Net.WebClient'
    - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))

  on_failure:
    - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version)-$(Get-Date -format HHmmss)-failed"    
    - ps: $wc = New-Object 'System.Net.WebClient'
    - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))